#!/bin/bash
protected_branch="main"
allowed_child="dev"

while read oldrev newrev refname; do
    branch=$(git rev-parse --symbolic --abbrev-ref "$refname")
    parent=$(git show-branch --merge-base $branch)

    if [[ $branch != "$allowed_child" && $parent == $protected_branch ]]; then
        echo "Error: 'dev' is the only branch name allowed off 'main'."
        exit 1
    fi
done