name: validate-commits

on:
  push:
    branches:
        - '*'
  pull_request:

jobs:
  validate-commits:
    name: validate-commits
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Validate the latest commit message
        run: |
          # Get the commit message for HEAD
          commit_message=$(git log -1 --pretty=%s)
          echo "Checking commit: $commit_message"
          
          # Validate the commit message format
          if [[ ! "$commit_message" =~ ^(ci:|feature:|fix:|docs:|test:)\ .+ ]]; then
            echo "❌ Commit message does not follow the required format: $commit_message"
            exit 1
          fi