name: Validate Commit Messages

on:
  push:
  pull_request:

jobs:
  validate-commits:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Validate commit messages
        run: |
          git log --format='%s' HEAD~$(git rev-list --count HEAD^)..HEAD | while read -r line; do
            echo "Checking commit: $line"
            if [[ ! "$line" =~ ^(ci:|feature:|fix:|docs:|test:)\ .+ ]]; then
              echo "❌ Commit message does not follow the required format: $line"
              exit 1
            fi
          done